### ISSUE TITLE
Release it!

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-f5bigip#1]
Tracking items needed to release this:
- [x] Add tests - borrow from https://github.com/pulumi/examples/pull/201 as possible.
- [x] Tag v0.1.0
- [x] Publish docs (https://github.com/pulumi/docs/pull/839)
- [x] Blog post draft
  - Draft at https://gist.github.com/clstokes/d1c65b7021d81ce0147310818185b6e7.
- [x] Merge examples PR (https://github.com/pulumi/examples/pull/201)

**Comment by clstokes** [comment]
Blog post draft is at https://gist.github.com/clstokes/d1c65b7021d81ce0147310818185b6e7 - _checking_ this off in the issue checlkist.

**Comment by lukehoban** [comment]
Done.
