### ISSUE TITLE
Preview with no changes after initial update proposes changes

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi-f5bigip#21]
After doing the initial deployment of a project, our integration test framework runs an empty preview and update and expects that doing so will show no changes to the infrastructure.

Recently (sometime within the past two weeks) this part of the test started to fail:

https://travis-ci.com/pulumi/pulumi-f5bigip/builds/121779295#L1476-L1503

Here we see a proposed diff to interval.  For now I am going to update the test to allow this but we should understand if this is something we can control to have a better experience here.

**Comment by pgavlin** [comment]
Closing this out for now--feel free to reopen if this is still a problem.
